export default {
  facebook: require('../assets/img/fb.png'),
  google: require('../assets/img/google.png'),
  apple: require('../assets/img/apple.png'),
  cloth1: require('../assets/img/cloth1.png'),
  shoe1: require('../assets/img/shoe1.png'),
  mkt1: require('../assets/img/mkt1.png'),
  store1: require('../assets/img/store1.png'),
  successIcon: require('../assets/img/successIcon.png'),
  errorIcon: require('../assets/img/errorIcon.png'),
  home: require('../assets/img/home.png'),
  search: require('../assets/img/search.png'),
  orders: require('../assets/img/orders.png'),
  profile: require('../assets/img/profile.png'),
  gadget: require('../assets/img/gadget.png'),
  cart: require('../assets/img/cart.png'),
  utensil: require('../assets/img/utensil.png'),
  assesory: require('../assets/img/assesory.png'),
  pp: require('../assets/img/pp.png'),
  walletBg: require('../assets/img/walletBg.png'),

  icons: {
    location: require('../assets/icons/location.png'),
    editUser: require('../assets/icons/editUser.png'),
    wallet: require('../assets/icons/wallet.png'),
    scan: require('../assets/icons/scan.png'),
    people: require('../assets/icons/people.png'),
    support: require('../assets/icons/support.png'),
    lock: require('../assets/icons/lock.png'),
    logout: require('../assets/icons/logout.png'),
    trash: require('../assets/icons/trash.png'),
    mail: require('../assets/icons/mail.png'),
    phone: require('../assets/icons/phone.png'),
    camera: require('../assets/icons/camera.png'),
    moneyIn: require('../assets/icons/moneyIn.png'),
    moneyOut: require('../assets/icons/moneyOut.png'),
    request: require('../assets/icons/request.png'),
    ongoing: require('../assets/icons/ongoing.png'),
  },
};
